---
- name: Configuraci칩n de Nginx, PHP-FPM y MySQL
  hosts: tu_servidor
  become: true
  tasks:
    - name: Actualizar repositorios
      apt:
        update_cache: yes

    - name: Instalar Nginx, PHP-FPM y MySQL
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - php-fpm
        - php-mysql
        - mysql-server
        - python3-mysqldb  # Dependencia de Ansible para MySQL
        - mysql-client

    - name: Copiar archivo de configuraci칩n de Nginx
      template:
        src: php.conf
        dest: /etc/nginx/default.d/php.conf
      notify:
        - Reiniciar Nginx

    - name: Copiar archivo de configuraci칩n de PHP-FPM
      template:
        src: php-fpm.conf.j2
        dest: /etc/php/{{ php_version }}/fpm/php-fpm.conf
      notify:
        - Reiniciar PHP-FPM

    - name: Configurar MySQL
      mysql_db:
        name: tu_base_de_datos
        state: present
      vars:
        login_user: root
        login_password: tu_contrase침a_de_root

  handlers:
    - name: Reiniciar Nginx
      service:
        name: nginx
        state: restarted

    - name: Reiniciar PHP-FPM
      service:
        name: php{{ php_version }}-fpm
        state: restarted
