---
- name: Configuración de Nginx, PHP-FPM y MySQL
  hosts: all
  become: true
  become_user: root
  vars:
    php_version: 8.2  # Ajusta según la versión de PHP que estés utilizando
    mysql_root_password: 'tu_contraseña_de_root'

  tasks:
    - name: Actualizar repositorios
      apt:
        update_cache: yes

    - name: Instalar Nginx, PHP-FPM y MySQL
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - php-fpm
        - php-mysql
   - name: Crear directorio web si no existe
      file:
        path: /home/admin/web/
        state: directory
        mode: '0755'

    - name: Copiar archivo de configuración de Nginx
      copy:
        src: default
        dest: /etc/nginx/sites-enabled/
      notify:
        - Reiniciar Nginx

    - name: Copiar archivos de la página web de forma recursiva
      copy:
        src: /home/admin/despliegue/ansible/pag/
        dest: /home/admin/web/
      notify:
        - Reiniciar Nginx

    - name: Copiar archivo de configuración de PHP-FPM
      template:
        src: www.conf
        dest: /etc/php/{{ php_version }}/fpm/pool.d/
      notify:
        - Reiniciar PHP-FPM

  handlers:
    - name: Reiniciar Nginx
      service:
        name: nginx
        state: restarted

    - name: Reiniciar PHP-FPM
      service:
        name: php{{ php_version }}-fpm
        state: restarted
